# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [56]:
import pandas as pd

ds = pd.read_csv(" https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")

ds

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [57]:
# Identify the dimensions of the dataset by determining the number of rows and columns it contains.

ds.shape

(4008, 11)

In [58]:
#Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable.
#You should also provide suggestions for fixing any incorrect data types.

ds.dtypes

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [59]:
#Identify the number of unique values for each column and determine which columns appear to be categorical.
#You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
ds['Customer'].nunique(), ds['ST'].nunique(), ds['GENDER'].nunique(), ds['Education'].nunique(), ds['Customer Lifetime Value'].nunique(), ds['Income'].nunique()

(1071, 8, 5, 6, 1027, 774)

In [60]:
display(ds["ST"].unique())
display(ds["GENDER"].unique())
display(ds["Education"].unique())
display(ds["Number of Open Complaints"].unique())
display(ds["Policy Type"].unique())
display(ds["Vehicle Class"].unique())

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA', nan], dtype=object)

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

array(['Master', 'Bachelor', 'High School or Below', 'College',
       'Bachelors', 'Doctor', nan], dtype=object)

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan],
      dtype=object)

array(['Personal Auto', 'Corporate Auto', 'Special Auto', nan],
      dtype=object)

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury SUV', 'Sports Car',
       'Luxury Car', nan], dtype=object)

In [61]:
#Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns.
#You should also provide your conclusions based on these summary statistics.

ds.describe()

             Income  Monthly Premium Auto  Total Claim Amount
count   1071.000000           1071.000000         1071.000000
mean   39295.701214            193.234360          404.986909
std    30469.427060           1601.190369          293.027260
min        0.000000             61.000000            0.382107
25%    14072.000000             68.000000          202.157702
50%    36234.000000             83.000000          354.729129
75%    64631.000000            109.500000          532.800000
max    99960.000000          35354.000000         2893.239678

In [62]:
# Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [63]:
display(ds['ST'].describe())
display(ds['GENDER'].describe())
display(ds['Education'].describe())
display(ds['Customer Lifetime Value'].describe())
display(ds['Number of Open Complaints'].describe())
display(ds["Policy Type"].describe())
display(ds["Vehicle Class"].describe())

count       1071
unique         8
top       Oregon
freq         320
Name: ST, dtype: object

count     954
unique      5
top         F
freq      457
Name: GENDER, dtype: object

count         1071
unique           6
top       Bachelor
freq           324
Name: Education, dtype: object

count           1068
unique          1027
top       445811.34%
freq               4
Name: Customer Lifetime Value, dtype: object

count       1071
unique         6
top       1/0/00
freq         830
Name: Number of Open Complaints, dtype: object

count              1071
unique                3
top       Personal Auto
freq                780
Name: Policy Type, dtype: object

count              1071
unique                6
top       Four-Door Car
freq                576
Name: Vehicle Class, dtype: object

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [64]:
# top 5 less common customer locations
location_counts = ds['ST'].value_counts()

location_counts

Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: ST, dtype: int64

In [65]:
Series_loaction_counts = pd.Series(location_counts, name = 'locations')

Series_loaction_counts

Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: locations, dtype: int64

In [66]:
top_less_common = Series_loaction_counts.sort_values(ascending = True)

top_less_common_5 = top_less_common.head(5)

top_less_common_5

AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: locations, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [67]:
ds.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [77]:
# The sales team wants to know the total number of policies sold for each type of policy
# Create a pandas Series object that contains the policy types and their total number of policies sold,
# and then retrieve the policy type with the highest number of policies sold.


value_policy_type = ds['Policy Type'].value_counts()

policy_series = pd.Series(value_policy_type, name = 'Policy Type')

display(policy_series)


policy_series.idxmax()

Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: Policy Type, dtype: int64

'Personal Auto'

In [80]:
ds.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [ ]:
personal_auto = ds.loc[ds['Policy Type'] == 'Personal Auto']
auto_policy = personal_auto.loc[0:1071,"Income":"Policy Type"]  # não percebo o que está dentro se S.B.

auto_policy

In [98]:

mean_auto_policy = auto_policy.groupby ('Policy Type')['Income'].mean()

mean_corporate_policy

Policy Type
Corporate Auto    41390.311966
Name: Income, dtype: float64

In [ ]:
corporate_auto = ds.loc[ds['Policy Type'] == 'Corporate Auto']

corporate_policy = corporate_auto.loc[0:1071, "Income":"Policy Type"]


corporate_policy

In [99]:
mean_corporate_policy = corporate_policy.groupby ('Policy Type')['Income'].mean()

mean_corporate_policy

Policy Type
Corporate Auto    41390.311966
Name: Income, dtype: float64

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [ ]:
# Your goal is to identify customers with a high policy claim amount.